name: Reusable Workflow

on:
  workflow_call: # Allows this workflow to be called from another workflow

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from the reusable workflow!"
